version: '3.8'

services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - 55555:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: